[package]
name = "ria"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[workspace]
members = [
  "mandelbrot",
  "grep-lite",
  "cubesat",
  "bitpats",
  "memory",
  "particles",
  "files",
  "fview",
  "actionkv",
]
